---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-web-application-db
  namespace: demo-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      name: go-web-db
  template:
    metadata:
      labels:
        name: go-web-db
    spec:
      containers:
        - name: db
          image: mysql:latest
          imagePullPolicy: IfNotPresent
#          resources:
#            requests:
#              ephemeral-storage: "2Gi"
#            limits:
#              ephemeral-storage: "4Gi"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "test"
            - name: MYSQL_DATABASE
              value: "test"
            - name: MYSQL_USER
              value: "test"
            - name: MYSQL_PASSWORD
              value: "test"
