---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-service-ingress
  namespace: demo-kube
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "demo-letsencrypt"
spec:
  tls:
    - hosts:
      - api.health-check.cf
      - health-check.cf
      secretName: quickstart-demo-tls
  rules:
    - host: api.health-check.cf
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: go-web-service
                port:
                  number: 3000
    - host: health-check.cf
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: demo-web
                port:
                  number: 80

