---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: demo-letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: khangjig.812@gmail.com
    privateKeySecretRef:
      name: demo-letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
